### ISSUE TITLE
go get fails - errors

### ISSUE THREAD

**Issue by tomazbracic** [divan/expvarmon#13]
Hi,

can you help me with this... "go get github.com/divan/expvarmon" fails. I am attaching the output of failed installation. 

http://pastebin.com/cTEyw3y1

Thanks,
Tomaz

**Comment by divan** [comment]
Oh, thanks for reporting. It's TermUI changed it's API. Going to fix it.

**Comment by divan** [comment]
Should be ok now with pinned dependency via gopkg.in.
https://github.com/divan/expvarmon/commit/383ee494c1dee0a8062137d81e08c6b18c80af13
