### ISSUE TITLE
Which license applies to this repo

### ISSUE THREAD

**Issue by ifraixedes** [divan/expvarmon#18]
I'm wondering which license applies to this repo.

Could you specify any to avoid issues with Laws interpretations?

If there's one announced somewhere, my apologies, but I couldn't find it.

Thanks for considering

**Comment by jpeddicord** [comment]
I'm a little confused here as well. I see in some of @divan's other repos that MIT or WTFPL are used, but this repo is missing one.

**Comment by ifraixedes** [comment]
Yes, it should be clarified for the sake of the people who wants to use or contribute.

**Comment by divan** [comment]
Oh, I've totally missed. Thanks for bringing it up, guys!
I usually choose MIT licence, though I'm not really licensing-savvy. Any objections against choosing MIT?

**Comment by ifraixedes** [comment]
MIT is my choice, so it looks good to me

**Comment by divan** [comment]
Thanks again!
https://github.com/divan/expvarmon/pull/28
