### ISSUE TITLE
Unable to clone https://gopkg.in/gizak/termui.v1 during build

### ISSUE THREAD

**Issue by borud** [divan/expvarmon#25]
Not sure if this is a transient error or a permanent error.

**Comment by santagada** [comment]
its a permanent error, termui moved to github https://github.com/gizak/termui

**Comment by divan** [comment]
@borud @santagada hey, thanks for opening an issue. TermUI has been always at github, gopkg.in is a service that "pin" versions. 

I suppose that gopkg.in had some downtime, hence the error. Now it works for me, can you please check it again?

**Comment by santagada** [comment]
they say on their github that the recomended way to use termui now is go get the master branch:

"
master mirrors v2 branch, to install:

go get -u github.com/gizak/termui
It is recommanded to use locked deps by using glide: move to termui src directory then run glide up.

For the compatible reason, you can choose to install the legacy version of termui:

go get gopkg.in/gizak/termui.v1
"

**Comment by santagada** [comment]
it still doesn't work for me:

"
go get -u github.com/divan/expvarmon
# cd .; git clone https://gopkg.in/gizak/termui.v1 /Users/santagada/go/src/gopkg.in/gizak/termui.v1
Cloning into '/Users/santagada/go/src/gopkg.in/gizak/termui.v1'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/gizak/termui.v1: exit status 128
"

**Comment by ysqi** [comment]
me too.
```sh
go get github.com/divan/expvarmon
package gopkg.in/gizak/termui.v1: unrecognized import path "gopkg.in/gizak/termui.v1" (parse https://gopkg.in/gizak/termui.v1?go-get=1: no go-import meta tags ())
```

**Comment by divan** [comment]
@aprice oh, wow, thanks for the heads up. I'll check this asap and will refactor code to use the latest termui (something I should have done a long time ago). Thanks again.

**Comment by divan** [comment]
I pushed changes to https://github.com/divan/expvarmon/tree/termui-master branch. Could you please double check it works properly? I'll merge it with master asap.

**Comment by powo** [comment]
```
[powo@zion expvarmon (termui-master)]
$ go get github.com/gizak/termui

[powo@zion expvarmon (termui-master)]
$ go build
# github.com/divan/expvarmon
./ui_multi.go:12:14: undefined: termui.Paragraph
./ui_multi.go:13:14: undefined: termui.Paragraph
./ui_multi.go:14:14: undefined: termui.List
./ui_multi.go:15:16: undefined: termui.List
./ui_multi.go:16:14: undefined: termui.Sparklines
./ui_multi.go:17:14: undefined: termui.Sparklines
```

**Comment by divan** [comment]
@powo `go get -u github.com/gizak/termui` perhaps? (without `-u` go get will not download an updated version to GOPATH).
PS. I have branch with modules support, that should be the right way to do things, but let's do one thing at a time.

**Comment by divan** [comment]
Okay, in between the messages in this thread, ["The Great Rewrite"](https://github.com/gizak/termui/commit/958a28575d7411492d25e42da3ad5a6e5947d9a4) has happened in termui (again).

Going to fix that and add go.mod.

**Comment by powo** [comment]
works :+1:

**Comment by jimmysawczuk** [comment]
Works for me too. 👍
