### ISSUE TITLE
unreadable code in centos 7 nimimium instalation

### ISSUE THREAD

**Issue by jianjyan** [divan/expvarmon#26]
![e5 pz 7uy k9p noo uj q](https://user-images.githubusercontent.com/9912473/26964343-9fa5e2f6-4d23-11e7-94e7-006306612e84.png)

**Comment by divan** [comment]
Hi. This is definitely an issue with your locale settings and/or terminal settings.

Does it change if set LANG env variable before?
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
expvarmon -self
```

**Comment by jianjyan** [comment]
![image](https://user-images.githubusercontent.com/9912473/27077304-3491e752-5062-11e7-8ff9-e1e03d831d21.png)

**Comment by jianjyan** [comment]
Hi, sorry about this, the problem is the encoding setting of Securecrt.
