### ISSUE TITLE
Update Installation Guide

### ISSUE THREAD

**Issue by omidnasiri** [divan/expvarmon#39]
To install expvarmon it's mentioned in the documentation to use `go get` which belongs to the pre-modules era
Now a days (since 2018 and Go 1.11) you need to use
```
go install github.com/divan/expvarmon@latest
```
and of cource having `$GOPATH/bin` in `$PATH`
to be able to install this awesome app

**Comment by divan** [comment]
Done. https://github.com/divan/expvarmon/commit/8e0b3d2778b3bb505fbfd14707ad52e68443e330
