### ISSUE TITLE
Ability to use non-standard endpoint URL

### ISSUE THREAD

**Issue by tleyden** [divan/expvarmon#9]
The program I'm trying monitor exposes the expvars at the non-standard `http://host:4985/_expvar` endpoint rather than the standard `http://localhost:4985/debug/vars` endpoint.

I tried this but it didn't work:

```
expvarmon -ports="http://localhost:4985/_expvar"
no ports specified. Use -ports arg to specify ports of Go apps to monitor
Usage of expvarmon:
   .. etc
```

As a feature request, would it be possible to add a new arg like `-endpoint` which would customize how the endpoint URL is constructed?

**Comment by divan** [comment]
Hey. yes, definitely it'd be easy to add. It can be even env variable (like EXPVARMON_ENDPOINT) to keep flag list as short as possible.
Your initial guess (allow URI path overwrite in 'ports' arg) probably can be an option also.
I'll take a look.

**Comment by tleyden** [comment]
Either would work for me!

**Comment by divan** [comment]
Added customizable endpoints in master, please check it out.

Now there are two ways to override endpoints:
 - use -endpoint flag. It will override endpoint for all hosts/ports
 - specifying endpoint in URL - like `-ports http://localhost:1234/_expvar`. It will override -endpoint flag for this url only, others remain the same.

**Comment by tleyden** [comment]
Thanks!
